### ISSUE TITLE
The DOC module

### ISSUE THREAD

**Issue by PKUCSS** [alinlab/MASKER#3]
Thanks for your excellent idea and implementation first.
I mentioned that 1 vs rest structure was used for OoD Detection in the paper, but currently it's not included in this repo. Could you please public the part for the community to reprouduce the results? Thank you very much!

**Comment by sangwoomo** [comment]
Hi @PKUCSS,

the 1-vs-rest classifier is implemented [here](https://github.com/alinlab/MASKER/blob/master/training/base.py#L35).
